config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  post '/guest_sign_in', to: 'sessions#new_guest'
  get 'auth/:provider/callback', to: 'sessions#create'
  get "/auth/failure", to: "sessions#failure"
  resources :users do
    member do
      get :following, :followers
      delete :delete_profile_image, :delete_avatar
    end
  end
  resources :microposts
  resources :choices, only: [:post, :destroy, :edit, :update] do
    resource :vote, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @microposts = Micropost.all.eager_load(user: {avatar_attachment: :blob}).with_attached_image.sorted_desc.page(params[:page])
    @colors = ['post_details_1','post_details_2', 'post_details_3', 'post_details_4']
  end

  def help
  end

  def about
  end
end

app/views/static_pages/_choice.html.erb
<% if logged_in? && current_user.voted?(choice) %>
  <div class= "choice_button">
    <div class="judgement-btn">
    <%= link_to choice.user do %>
      <% if choice.user %>
        <% if choice.user.avatar.attached? %>
          <%= image_tag(choice.user.avatar.variant(resize: "40x40").processed, class: "avatar ") %>
        <% else %>
          <%= gravatar_for choice.user %>
        <% end %>
      <% end %>
    <% end %>
    </div>
    <button class="voted">
      <%= link_to choice_vote_path(choice.id), method: :delete, remote: true do %>
        <p><%= choice.name %></p>
      <% end %>
    </button>
  </div>
  <div class="judgement-btn">
  <% if choice.micropost.user != current_user && choice.user == current_user %>
    <%= link_to '編集', edit_choice_path(choice.id), remote: true, class: "btn-border-sm"%>
  <%end%>
  </div>
<% else %>
  <div class= "choice_button">
    <div class="judgement-btn">
    <%= link_to choice.user do %>
      <% if choice.user %>
        <% if choice.user.avatar.attached? %>
          <%= image_tag(choice.user.avatar.variant(resize: "40x40").processed, class: "avatar ") %>
        <% else %>
          <%= gravatar_for choice.user %>
        <% end %>
      <% end %>
    <% end %>
    </div>
    <button class="vote">
      <%= link_to choice_vote_path(choice.id), method: :post, remote: true do %>
        <p><%= choice.name %></p>
      <% end %>
    </button>
  </div>
  <div class="judgement-btn">
  <% if choice.micropost.user != current_user && choice.user == current_user %>
    <%= link_to '編集', edit_choice_path(choice.id), remote: true, class: "btn-border-sm"%>
  <%end%>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>About | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
      is a <a href="https://railstutorial.jp/#ebook">book</a> and
      <a href="https://railstutorial.jp/#screencast">screencast</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Help | Ruby on Rails Tutorial Sample App</title>
  </head>
  <body>
    <h1>Help</h1>
    <p>  Get help on the Ruby on Rails Tutorial at the
      <a href="https://railstutorial.jp/help">Rails Tutorial help
      page</a>.
      To get help on this sample app, see the
      <a href="https://railstutorial.jp/#ebook">
      <em>Ruby on Rails Tutorial</em> book</a>.
    </p>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class="home_container">
<%= render 'layouts/side-bar' %>
  <% @microposts.each_with_index do |micropost, i| %>
    <div class="item">
        <div class="<%= @colors.shuffle[i % 4] %>">
          <div class="user_info">
            <% if micropost.user.avatar.attached? %>
              <%= image_tag micropost.user.avatar.variant(resize: "50x50").processed, class: "avatar " %>
            <% else %>
              <%= gravatar_for micropost.user %>
            <% end %>
            <span class="user"><%= link_to micropost.user.name, micropost_path(micropost) %></span>
          </div>
            <% if micropost.image.attached? %>
              <div class="picture">
                <%= link_to micropost.image, "data-lightbox" => micropost.image do %>
                  <%= image_tag micropost.image.variant(resize: "500x500").processed, class: "img" %>
                <% end %>
              </div>
            <% end %>
          <div class="comment">
            <p><%= micropost.content %></p>
          </div>
            <% micropost.choices.eager_load(:user)&.each do |choice| %>
              <div id="choice_<%= choice.id %>">
                <%= render 'choice', choice: choice %>
              </div>
            <% end %>
        </div>
    </div>
  <% end %>
</div>
<div class="paginate_container">
  <%= paginate @microposts %>
</div>

<script>
var $container = $('.home_container');
	$container.imagesLoaded(function(){
		$container.masonry({
      itemSelector: '.item',
		});
  });
</script>