config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  post '/guest_sign_in', to: 'sessions#new_guest'
  get 'auth/:provider/callback', to: 'sessions#create'
  get "/auth/failure", to: "sessions#failure"
  resources :users do
    member do
      get :following, :followers
      delete :delete_profile_image, :delete_avatar
    end
  end
  resources :microposts
  resources :choices, only: [:post, :destroy, :edit, :update] do
    resource :vote, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :micropost
  has_many :votes, dependent: :destroy
  validates_presence_of :micropost
  validates :name, presence: true, length: { maximum: 140 }
  belongs_to :user
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  before_action :set_choice, only:[:edit, :update, :destroy]
  def destroy
    @choice.destroy
    flash[:success] = "ボタンを削除しました"
    redirect_to micropost_path(@choice.micropost.id)
  end

  def edit
  end

  def update
    if @choice.update(choice_params)
      flash[:success] = "ボタンを更新しました"
      redirect_to micropost_path(@choice.micropost.id)
    end
  end

  private
  
    def choice_params
      params.require(:choice).permit(:id, :name, :user_id)
    end

    def set_choice
      @choice = Choice.find(params[:id])
    end
end

app/views/choices/_edit.html.erb
<div class="modal-dialog">
  <div class="sign_up col-md-8 col-md-offset-2">
    <%= form_with model: @choice, local: true do |f|%> 
      <%= f.text_area :name, class: "number" %>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= link_to "削除",choice_path(@choice), method: :delete, data: { confirm: "『#{f.object.name}』を削除しますか？", cancel: 'やめる', title: '削除確認' }, class: "btn-border-sm"%>
      <%= f.submit "更新", class: "btn-border-sm" %>
    <% end %>
  </div>
</div>

app/views/choices/edit.html.erb
<%= form_with model: @choice, local: true do |f|%> 
  <%= f.text_area :name, class: "number" %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= link_to "削除",choice_path(@choice), method: :delete, data: { confirm: "『#{f.object.name}』を削除しますか？", cancel: 'やめる', title: '削除確認' }, class: "btn-border-sm"%>
  <%= f.submit "更新", class: "btn-border-sm" %>
<% end %>