config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  post '/guest_sign_in', to: 'sessions#new_guest'
  get 'auth/:provider/callback', to: 'sessions#create'
  get "/auth/failure", to: "sessions#failure"
  resources :users do
    member do
      get :following, :followers
      delete :delete_profile_image, :delete_avatar
    end
  end
  resources :microposts
  resources :choices, only: [:post, :destroy, :edit, :update] do
    resource :vote, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_one_attached :avatar
  has_one_attached :profile_image
  has_many :choices
  has_many :microposts, dependent: :destroy
  has_many :votes
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy,
                                  inverse_of: :follower
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy,
                                   inverse_of: :followed
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  attr_accessor :remember_token
  validates :name, presence: true, length: { maximum: 50 }, unless: :uid?
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  before_save :downcase_email, unless: :uid?
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false },
                    unless: :uid?
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, on: :password, unless: :uid?
  validate  :validate_avatar, :validate_profile_image
  def downcase_email
    self.email = email.downcase
  end

  def self.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def self.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    self.update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?

    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    self.update_attribute(:remember_digest, nil)
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def voted?(choice)
    votes.where(choice_id: choice.id).exists?
  end

  def validate_avatar
    return unless avatar.attached?

    if avatar.blob.byte_size > 10.megabytes
      avatar.purge
      errors.add(:avatar, 'ファイルのサイズが大きすぎます(10MB以内)')
    elsif !avatar_image?
      avatar.purge
      errors.add(:avatar, 'ファイルが対応している画像データではありません')
    end
  end

  def validate_profile_image
    return unless profile_image.attached?

    if profile_image.blob.byte_size > 10.megabytes
      profile_image.purge
      errors.add(:profile_image, 'ファイルのサイズが大きすぎます(10MB以内)')
    elsif !profile_image?
      profile_image.purge
      errors.add(:profile_image, 'ファイルが対応している画像データではありません')
    end
  end

  private

  def self.guest
    find_or_create_by!(name: 'ゲスト', email: 'guest1@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end

  def self.find_or_create_from_auth(auth)
    provider = auth[:provider]
    uid = auth[:uid]
    name = auth[:info][:name]
    image = auth[:info][:image]
    image_url = auth[:info][:image]
    uri = URI.parse(image_url)
    image = uri.open
    password = SecureRandom.urlsafe_base64
    email = User.dummy_email(auth)
    self.find_or_create_by(provider: provider, uid: uid) do |user|
      user.name = name
      user.avatar.attach(io: image, filename: "#{user.name}_profile.png")
      user.password = password
      user.email = email
    end
  end

  def self.dummy_email(auth)
    "#{auth.uid}-#{auth.provider}@example.com"
  end

  def avatar_image?
    %w[image/jpg image/jpeg image/gif image/png].include?(avatar.blob.content_type)
  end

  def profile_image?
    %w[image/jpg image/jpeg image/gif image/png].include?(profile_image.blob.content_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :currect_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy
  before_action :set_users, only: [:following, :followers]
  before_action :set_delete, only: [:delete_profile_image, :delete_avatar]

  def index
    @users = User.includes(avatar_attachment: :blob).paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.all.with_attached_image.sorted_desc.page(params[:page])
    @colors = %w[post_details_1 post_details_2 post_details_3 post_details_4]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save(context: :password)
      log_in @user
      flash[:succces] = "新規登録完了しました"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:succces] = "編集しました"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:succces] = "削除されました"
    redirect_to users_url
  end

  def delete_profile_image
  end

  def delete_avatar
  end

  def following
  end

  def followers
  end

  private

  def set_users
    @user = User.find(params[:id])
    users = action_name == 'following' ? @user.following : @user.followers
    @title = action_name == 'following' ? "フォロー中" : "フォロワー"
    @users = users.paginate(page: params[:page])
    render 'show_follow'
  end

  def set_delete
    @user = User.find(params[:id])
    action_name == 'delete_profile_image' ? @user.profile_image.purge : @user.avatar.purge
    redirect_to @user
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :introduction, :profile_image, :avatar)
  end

  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインして下さい"
      redirect_to login_url
    end
  end

  def currect_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user,options = {size: 80})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.name,class: "gravatar")
  end

  def gravatar_profile(user,options = {size: 110})
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.name,class: "gravatar_profile", id: "avatar_prev")
  end
end

app/views/users/_edit.html.erb
<%= form_with model: @user, local: true do |f|%>
  <div class="modal-dialog">
    <div class="profile_modal col-md-10 col-md-offset-2">
      <div class="profile_container">
        <div class="image_container">
          <span class="edit"><%= f.submit "更新", class: "btn-border-sm" %></span>
            <% if @user.profile_image.attached? %>
              <%= image_tag @user.profile_image.variant(resize: "400x400").processed, class: "image", id: :img_prev %>
            <% else %>
              <%= image_tag '/noimage.png', alt: 'プロフィール画像',class: "image", id: :img_prev %>
            <% end %>
          <label class="label">
            <i class="fa fa-image" ><%= f.file_field :profile_image, id: :user_img %></i>
            <%= link_to '削除', delete_profile_image_user_path, method: :delete, data: { confirm: 'プロフィール画像削除しますか?' } %>
          </label>
          <div class="avater_container_modal">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar.variant(resize: "100x100").processed, class: "avatar_profile", id: :avatar_prev %>
            <% else %>
              <%= gravatar_profile @user %>
            <% end %>
            <label class="label">
              <i class="fa fa-image" ><%= f.file_field :avatar, id: :avatar_img %></i>
              <%= link_to '削除', delete_avatar_user_path, method: :delete, data: { confirm: 'アバター画像削除しますか?' } %>
            </label>
          </div>
        </div>
        <div class="profile_user_info_modal">
          <div class="user_name">
            <%= f.label :name,"ユーザー名"%>
            <%= f.text_field :name, class:'form-control'%>
          </div>
        </div>
        <div class="introduction">
          <%= f.label :introduction,"自己紹介"%>
          <%= f.text_area :introduction, placeholder: "自己紹介文を記入して下さい",class: 'form-control'%>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#user_img").change(function(){
        readURL(this);
    });
  });
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#avatar_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#avatar_img").change(function(){
        readURL(this);
    });
  });
</script>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "Follow", class: "side_bar btn-border-sm" %>
<% end %>

app/views/users/_follow_unfollow.html.erb
<% if current_user != user %>
  <div class="follow_form_<%= user.id %> judgement-btn">
    <% if current_user.following?(user) %>
      <%= render partial: 'users/unfollow', locals: { user: user } %>
    <% else %>
      <%= render partial: 'users/follow', locals: { user: user } %>
    <% end %>
  </div>
<% end %>

app/views/users/_pie_chart.html.erb
<%= pie_chart micropost.choices.joins(:votes).map { |m| [m.name, m.votes.count] }.to_h, donut: true, messages: {empty: "投票はありません"} %>
<% micropost.choices&.each do |choice| %>
  <table>
    <tr>
      <th><%= choice.name %></th>
        <td><%= choice.votes.count %></td>
      </tr>
  </table>
<% end %>

app/views/users/_signup.html.erb
<div class="modal-dialog">
  <div class="sign_up col-md-8 col-md-offset-2">
  <h3>新規作成</h3>
    <%= form_for(@user,url: signup_path) do |f| %>
      <%= f.label :name,"ユーザー名"%>
      <%= f.text_field :name, class:'form-control'%>
      <%= f.label :email %>
      <%= f.email_field :email, class:'form-control'%>
      <%= f.label :password,"パスワード"%>
      <%= f.password_field :password, class: 'form-control' %>
      <%= f.label :password_confirmation,"パスワード確認" %>
      <%= f.password_field :password_confirmation,class: 'form-control'%>
      <div class="guest_login">
        <%= f.submit "新規作成", class: "btn-border" %>
        <p>
          <%= link_to '/auth/twitter', class: "btn btn-social btn-twitter" do %>
            <span class="fa fa-twitter"></span> Twitterアカウントでログイン
          <% end %>
        </p>
      </div>
    <% end %>
  </div>
</div>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id),html: { method: :delete },remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "side_bar btn-border-sm" %>
<% end %>

app/views/users/edit.html.erb
<%= form_with model: @user, local: true do |f|%>
  <div class="modal-dialog">
    <div class="profile_modal col-md-10 col-md-offset-2">
      <div class="profile_container">
        <%= render 'shared/error_messeges', object: f.object%>
        <div class="image_container">
          <span class="edit"><%= f.submit "更新", class: "btn-border-sm" %></span>
          <div id="" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
            <% if @user.profile_image.attached? %>
              <%= image_tag @user.profile_image.variant(resize: "400x400").processed, class: "image", id: :img_prev %>
            <% else %>
              <%= image_tag '/noimage.png', alt: 'プロフィール画像',class: "image", id: :img_prev %>
            <% end %>
          <label class="label">
            <i class="fa fa-image" ><%= f.file_field :profile_image, id: :user_img %></i>
            <%= link_to '削除', delete_profile_image_user_path, method: :delete, data: { confirm: 'プロフィール画像削除しますか?' } %>
          </label>
          <div class="avater_container_modal">
            <% if @user.avatar.attached? %>
              <%= image_tag @user.avatar.variant(resize: "100x100").processed, class: "avatar_profile", id: :avatar_prev %>
            <% else %>
              <%= gravatar_profile @user %>
            <% end %>
            <label class="label">
              <i class="fa fa-image" ><%= f.file_field :avatar, id: :avatar_img %></i>
              <%= link_to '削除', delete_avatar_user_path, method: :delete, data: { confirm: 'アバター画像削除しますか?' } %>
            </label>
          </div>
        </div>
        <div class="profile_user_info_modal">
          <div class="user_name">
            <%= f.label :name,"ユーザー名"%>
            <%= f.text_field :name, class:'form-control'%>
          </div>
        </div>
        <div class="introduction">
          <%= f.label :introduction,"自己紹介"%>
          <%= f.text_area :introduction, placeholder: "自己紹介文を記入して下さい",class: 'form-control'%>
        </div>
      </div>
    </div>
  </div>
<% end %>
<script type="text/javascript">
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#img_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#user_img").change(function(){
        readURL(this);
    });
  });
  $(function() {
    function readURL(input) {
        if (input.files && input.files[0]) {
        var reader = new FileReader();
        reader.onload = function (e) {
    $('#avatar_prev').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
        }
    }
    $("#avatar_img").change(function(){
        readURL(this);
    });
  });
</script>

app/views/users/edit.js.erb
$("#user-modal").html("<%= escape_javascript(render 'edit') %>")
$("#user-modal").modal("show") 

app/views/users/index.html.erb
<%= render 'layouts/side-bar' %>
<h1>All users</h1>
<% @users.each do |user| %>
  <div class="follow_list">
    <p class="gravatar_follow">
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar.variant(resize: "50x50").processed, class: "avatar " %>
      <% else %>
        <%= gravatar_for user %>
      <% end %>
    </p>
    <h4 class="user"><%= link_to user.name, user, data: { "turbolinks" => false } %></h4>
  </div>
<% end %>
<%= will_paginate %>

app/views/users/new.html.erb
<%= render 'layouts/side-bar' %>
<div class="sign_up col-md-4 col-md-offset-1">
  <h3>新規作成</h3>
  <%= form_for(@user,url: signup_path) do |f| %>
    <%= render 'shared/error_messeges', object: f.object%>
    <%= f.label :name,"ユーザー名"%>
    <%= f.text_field :name, class:'form-control'%>
    <%= f.label :email %>
    <%= f.email_field :email, class:'form-control'%>
    <%= f.label :password,"パスワード"%>
    <%= f.password_field :password, class: 'form-control' %>
    <%= f.label :password_confirmation,"パスワード確認" %>
    <%= f.password_field :password_confirmation,class: 'form-control'%>
    <div class="guest_login">
      <%= f.submit "新規作成", class: "btn-border" %>
      <p>
        <%= link_to '/auth/twitter', class: "btn btn-social btn-twitter" do %>
          <span class="fa fa-twitter"></span> Twitterアカウントでログイン
        <% end %>
      </p>
    </div>
  <% end %>
</div>

app/views/users/new.js.erb
$("#user-modal").html("<%= escape_javascript(render 'signup') %>")
$("#user-modal").modal("show")

app/views/users/show.html.erb
<div class="profile_container">
<%= render 'layouts/side-bar' %>
  <div class="item profile">
      <div class="image_container">
        <span class="edit"><%= link_to '編集', edit_user_path, remote: true, class: "btn-border-sm"%></span>
        <% if @user.profile_image.attached? %>
          <%= image_tag @user.profile_image.variant(resize: "400x400").processed, class: "image" %>
        <% else %>
          <%= image_tag '/noimage.png', alt: 'プロフィール画像',class: "image", id: :img_prev %>
        <% end %>
        <div class="avater_container">
          <% if @user.avatar.attached? %>
            <%= image_tag @user.avatar.variant(resize: "100x100").processed, class: "avatar_profile " %>
          <% else %>
            <%= gravatar_profile @user %>
          <% end %>
        </div>
      </div>
      <div class="profile_user_info">
        <div class="user_name">
          <p><%= @user.name %></p>
        </div>
        <div class="follow">
          <div class="follow_count">
            <a " href="<%= following_user_path(@user) %>">
              <strong id="following" class="stat">
                <%= @user.following.count %>
              </strong>
              フォロー中
            </a>
            <a href="<%= followers_user_path(@user) %>">
              <strong id="followers" class="stat">
                <%= @user.followers.count %>
              </strong>
              フォロワー
            </a>
          </div>
          <%= render partial: 'users/follow_unfollow', locals: { user: @user } %>
        </div>
      </div>
      <div class="introduction">
        <p><%= @user.introduction%></p>
      </div>
  </div>
  <% @microposts.each_with_index do |micropost, i| %>
    <div class="item">
        <div class="<%= @colors.shuffle[i % 4] %>">
          <div class="user_info">
            <% if micropost.user.avatar.attached? %>
              <%= image_tag micropost.user.avatar.variant(resize: "50x50").processed, class: "avatar " %>
            <% else %>
              <%= gravatar_for micropost.user %>
            <% end %>
            <span class="user"><%= link_to micropost.user.name, micropost_path(micropost) %></span>
          </div>
            <% if micropost.image.attached? %>
              <div class="picture">
                <%= link_to micropost.image, "data-lightbox" => micropost.image do %>
                  <%= image_tag micropost.image.variant(resize: "500x500"), class: "img" %>
                <% end %>
              </div>
            <% end %>
          <div class="comment">
            <p><%= micropost.content %></p>
          </div>
          <% micropost.choices.includes(user: {avatar_attachment: :blob})&.each do |choice| %>
            <div id="choice_<%= choice.id %>">
              <%= render 'static_pages/choice', choice: choice %>
            </div>
          <% end %>
        </div>
    </div>
  <% end %>
</div>
<div class="paginate_container">
  <%= paginate @microposts %>
</div>

<script>
var $container = $('.profile_container');
	$container.imagesLoaded(function(){
		$container.masonry({
      itemSelector: '.item',
		});
  });
</script>

app/views/users/show_follow.html.erb
<%= render 'shared/stats', user: @user %>
<h1><%= @title %></h1>
<% @users.each do |user| %>
  <div class="follow_list">
    <p class="gravatar_follow">
      <% if user.avatar.attached? %>
        <%= image_tag user.avatar.variant(resize: "50x50").processed, class: "avatar " %>
      <% else %>
        <%= gravatar_for user %>
      <% end %>
    </p>
    <h4 class="user"><%= link_to user.name, user %></h4>
  </div>
<% end %>
<%= will_paginate %>