config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  root 'static_pages#home'
  get 'static_pages/help'
  get 'static_pages/about'
  get  '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/login', to: 'sessions#destroy'
  post '/guest_sign_in', to: 'sessions#new_guest'
  get 'auth/:provider/callback', to: 'sessions#create'
  get "/auth/failure", to: "sessions#failure"
  resources :users do
    member do
      get :following, :followers
      delete :delete_profile_image, :delete_avatar
    end
  end
  resources :microposts
  resources :choices, only: [:post, :destroy, :edit, :update] do
    resource :vote, only: [:create, :destroy]
  end
  resources :relationships, only: [:create, :destroy]
end

app/views/layouts/_side-bar.html.erb
<div class="item">
  <div class="side-bar">
    <ul >
    <% if logged_in? %>
      <li><%= link_to "Home",root_path, data: { "turbolinks" => false } %></l>
      <li><%= link_to "My page",current_user, data: { "turbolinks" => false } %></li>
      <li><%= link_to "User list",users_path %></li>
      <li><%= link_to "Log out",login_path, method: :delete %></li>
    </ul>
      <%= link_to "Judgement?",new_micropost_path, remote: true, class: "side_bar btn-border" %>
      <% else %>
    <ul>
      <li><%= link_to "Home",root_path, data: { "turbolinks" => false } %></li>
      <li><%= link_to "Sign up",signup_path, remote: true %></li>
      <li><%= link_to "Login",login_path, remote: true %></li>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Judgement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>
    <script src="https://unpkg.com/imagesloaded@4/imagesloaded.pkgd.min.js"></script>
    <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.min.js"></script>
  </head>

  <body>
    <div class="container">
    <div id="user-modal" class="modal fade" tabindex="-1" role="dialog" aria-hidden="true"></div>
      <% flash.each do |message_type,message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </div>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>